/**
 * Fixtures-only trust anchor fingerprint map.
 *
 * **Not for production use.** These fingerprints belong to a local test CA +
 * TSA signing cert generated by `spec/generate-fixtures.ts`. They exist solely
 * to let test vectors in `spec/test-vectors/` be signed and verified without
 * depending on the real production CAs (FreeTSA, DigiCert).
 *
 * A CI check (`scripts/check-fingerprints-disjoint.ts`, ships in Unit 6)
 * asserts programmatically that this map and `src/trust-anchors/fingerprints.ts`
 * have empty set-intersection, so fixtures anchors can never pollute a
 * production verifier's trust set.
 *
 * **Status (v1.0-rc.1):** placeholder. `spec/generate-fixtures.ts` is a stub;
 * the real fixtures-CA + signed TSA tokens are tracked as the Unit 4b blocker
 * for `v1.0` stable.
 */
export const TRUST_ANCHOR_FINGERPRINTS_FIXTURES: Record<string, string> = {
  // Populated by `generate-fixtures.ts` once Unit 4b lands.
  // Key format: `<filename>.pem` → `<sha256(ski-bytes) hex>`.
};
