/**
 * Fixtures-only trust anchor fingerprint map.
 *
 * **Not for production use.** The fixtures CA under `test-ca.pem` is
 * generated by `spec/tools/fixtures-ca.ts` and is only referenced by the
 * `fail-trust-anchor-mismatch` test vector. A CI check asserts this map
 * has empty set-intersection with `src/trust-anchors/fingerprints.ts`
 * so a fixtures anchor cannot leak into a production verifier's trust set.
 *
 * Regenerated by `npm run fixtures:generate`. Do not hand-edit.
 */
export const TRUST_ANCHOR_FINGERPRINTS_FIXTURES: Record<string, string> = {
  'test-ca.pem': '672e1d0d7a8a0c7338b5d5781194d28b498ee16e3024b3fa4a30fcf0b85d9f1d',
};
