#!/usr/bin/env node
/**
 * Regenerate the four crypto-bearing reference test vectors under
 * `spec/test-vectors/`, plus the one fixtures CA PEM + its pinned
 * SHA-256 SKI fingerprint. Deterministic vectors (`fail-*` cases from
 * Unit 4a) are not touched.
 *
 * Run:
 *     npm run fixtures:generate
 *
 * Requires network: FreeTSA + DigiCert are contacted to mint real
 * RFC 3161 TimeStampTokens over the chosen Merkle roots. The resulting
 * vectors verify end-to-end against the production trust anchors already
 * pinned in `src/trust-anchors/`, so no verifier override is needed for
 * pass / partial cases — they exercise the same code path an end user
 * runs in anger.
 *
 * The `fail-trust-anchor-mismatch` vector uses a TimeStampToken signed
 * by the local fixtures CA (generated by `tools/fixtures-ca.ts`); its
 * issuer chain does not terminate at any PEM pinned in `src/`, so CMS
 * signature verification fails and the verdict is `fail`.
 */

import * as ed25519 from '@noble/ed25519';
import { sha256 } from '@noble/hashes/sha2.js';
import { bytesToHex, hexToBytes } from '@noble/hashes/utils.js';
import canonicalize from 'canonicalize';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { DIGICERT, FREETSA, fetchTsaToken } from './tools/fetch-tsa.js';
import { buildFixturesCa, signFixturesTimeStampToken } from './tools/fixtures-ca.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const VECTORS_DIR = resolve(__dirname, 'test-vectors');
const FIXTURES_DIR = resolve(__dirname, 'fixtures-trust-anchors');

// ---------------------------------------------------------------------------
// Helpers — RFC 6962 Merkle (mirrors src/merkle.ts exactly)
// ---------------------------------------------------------------------------

function leafHash(eventHash: string): string {
  const h = sha256.create();
  h.update(Uint8Array.from([0x00]));
  h.update(hexToBytes(eventHash));
  return bytesToHex(h.digest());
}

/** Compute the Merkle root for a single-leaf tree. */
function singleLeafRoot(eventHash: string): string {
  return leafHash(eventHash);
}

/** Compute SHA-256(canonicalize(event)) — the event_hash production rule. */
function eventHashFor(event: Record<string, unknown>): string {
  const canonical = canonicalize(event);
  if (canonical === undefined) throw new Error('canonicalize returned undefined');
  return bytesToHex(sha256(new TextEncoder().encode(canonical)));
}

// ---------------------------------------------------------------------------
// Ed25519 helpers (for tier2-pass server_signature)
// ---------------------------------------------------------------------------

function toBase64Url(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString('base64url');
}

async function generateSigningKey() {
  const privateKey = ed25519.utils.randomSecretKey();
  const publicKey = await ed25519.getPublicKeyAsync(privateKey);
  // Matches `computeFingerprint` in the platform: base64url(SHA-256(publicKey))[:16].
  const fingerprint = toBase64Url(sha256(publicKey)).slice(0, 16);
  return { privateKey, publicKey, fingerprint };
}

// ---------------------------------------------------------------------------
// Vector specifications
// ---------------------------------------------------------------------------

interface TsaAnchor {
  type: 'tsa_freetsa' | 'tsa_digicert';
  token: string;
  external_timestamp: string;
}

async function generateTier2Pass(fixturesInfo: { caSkiSha256Hex: string }): Promise<void> {
  console.log('[tier2-pass] building event + Merkle root');
  const event = {
    deal_id: 'deal-spec-vector',
    event_type: 'ACCEPT_TERMS',
    actor_user_id: 'user-spec-vector',
    actor_org_id: 'org-spec-vector',
    actor_role: 'talent',
    timestamp: '2026-04-17T00:00:00.000Z',
    prev_event_hash: null,
    metadata: { note: 'spec-vector: tier2-pass' },
    artifact_references: [],
  };
  const eventHash = eventHashFor(event);
  const root = singleLeafRoot(eventHash);

  console.log('[tier2-pass] generating Ed25519 signing key');
  const { privateKey, publicKey, fingerprint } = await generateSigningKey();
  const signature = await ed25519.signAsync(hexToBytes(eventHash), privateKey);

  console.log('[tier2-pass] requesting FreeTSA token…');
  const freetsa = await fetchTsaToken(FREETSA, root);
  console.log('[tier2-pass] requesting DigiCert token…');
  const digicert = await fetchTsaToken(DIGICERT, root);

  const bundle = {
    bundle_schema_version: 1,
    status: 'confirmed',
    event_hash: eventHash,
    event,
    server_signature: bytesToHex(signature),
    signing_key_id: fingerprint,
    signing_keys: [
      {
        fingerprint,
        public_key_base64url: toBase64Url(publicKey),
        status: 'active',
      },
    ],
    merkle_proof: { leaf_index: 0, siblings: [], root },
    anchors: [
      {
        type: 'tsa_freetsa',
        token: freetsa.tokenBase64Der,
        external_timestamp: freetsa.externalTimestamp,
      } as TsaAnchor,
      {
        type: 'tsa_digicert',
        token: digicert.tokenBase64Der,
        external_timestamp: digicert.externalTimestamp,
      } as TsaAnchor,
    ],
    partial_anchors_reason: [],
  };

  writeVector('tier2-pass.json', bundle);
}

async function generateTier1Pass(): Promise<void> {
  console.log('[tier1-pass] building Tier 1 proof');
  // Tier 1 has only event_hash, merkle_proof, anchors — no event / sig / keys.
  // Use a deterministic synthetic hash so the committed vector's Merkle root
  // is reproducible without needing to share real event data.
  const eventHash = bytesToHex(sha256(new TextEncoder().encode('spec-vector:tier1-pass'))); // 64-char hex
  const root = singleLeafRoot(eventHash);

  console.log('[tier1-pass] requesting FreeTSA token…');
  const freetsa = await fetchTsaToken(FREETSA, root);
  console.log('[tier1-pass] requesting DigiCert token…');
  const digicert = await fetchTsaToken(DIGICERT, root);

  const bundle = {
    bundle_schema_version: 1,
    status: 'confirmed',
    event_hash: eventHash,
    merkle_proof: { leaf_index: 0, siblings: [], root },
    anchors: [
      {
        type: 'tsa_freetsa',
        token: freetsa.tokenBase64Der,
        external_timestamp: freetsa.externalTimestamp,
      } as TsaAnchor,
      {
        type: 'tsa_digicert',
        token: digicert.tokenBase64Der,
        external_timestamp: digicert.externalTimestamp,
      } as TsaAnchor,
    ],
    partial_anchors_reason: [],
  };

  writeVector('tier1-pass.json', bundle);
}

async function generatePartialMissingAnchor(): Promise<void> {
  console.log('[partial-missing-anchor] building Tier 1 with only DigiCert present');
  const eventHash = bytesToHex(sha256(new TextEncoder().encode('spec-vector:partial-missing-anchor')));
  const root = singleLeafRoot(eventHash);

  console.log('[partial-missing-anchor] requesting DigiCert token (FreeTSA declared missing)…');
  const digicert = await fetchTsaToken(DIGICERT, root);

  const bundle = {
    bundle_schema_version: 1,
    status: 'partial',
    event_hash: eventHash,
    merkle_proof: { leaf_index: 0, siblings: [], root },
    anchors: [
      {
        type: 'tsa_digicert',
        token: digicert.tokenBase64Der,
        external_timestamp: digicert.externalTimestamp,
      } as TsaAnchor,
    ],
    // Non-empty partial_anchors_reason with all checks passing triggers the
    // "partial" row in the verdict truth table (§5 of the spec).
    partial_anchors_reason: ['tsa_freetsa'],
  };

  writeVector('partial-missing-anchor.json', bundle);
}

async function generateTrustAnchorMismatch(fixturesCa: {
  fixtures: Awaited<ReturnType<typeof buildFixturesCa>>;
}): Promise<void> {
  console.log('[fail-trust-anchor-mismatch] signing token with local fixtures CA');
  const eventHash = bytesToHex(
    sha256(new TextEncoder().encode('spec-vector:fail-trust-anchor-mismatch')),
  );
  const root = singleLeafRoot(eventHash);

  const fixturesToken = await signFixturesTimeStampToken(fixturesCa.fixtures, root);

  const bundle = {
    bundle_schema_version: 1,
    status: 'confirmed',
    event_hash: eventHash,
    merkle_proof: { leaf_index: 0, siblings: [], root },
    anchors: [
      // Claim this is a FreeTSA anchor so the verifier routes it through the
      // TSA verification path. The embedded token is signed by the local
      // fixtures CA, which is not pinned — CMS sig verification fails.
      {
        type: 'tsa_freetsa',
        token: fixturesToken.tokenBase64Der,
        external_timestamp: fixturesToken.genTime.toISOString(),
      } as TsaAnchor,
    ],
    partial_anchors_reason: [],
  };

  writeVector('fail-trust-anchor-mismatch.json', bundle);
}

// ---------------------------------------------------------------------------
// I/O
// ---------------------------------------------------------------------------

function writeVector(filename: string, bundle: Record<string, unknown>): void {
  const path = resolve(VECTORS_DIR, filename);
  writeFileSync(path, JSON.stringify(bundle, null, 2) + '\n');
  console.log(`  wrote ${filename}`);
}

async function main(): Promise<void> {
  console.log('[fixtures] building local CA + TSA signing cert');
  const fixtures = await buildFixturesCa();

  // Write the fixtures CA PEM + fingerprints file.
  writeFileSync(resolve(FIXTURES_DIR, 'test-ca.pem'), fixtures.caCertPem);
  console.log(`  wrote fixtures-trust-anchors/test-ca.pem`);
  writeFileSync(
    resolve(FIXTURES_DIR, 'fingerprints.ts'),
    `/**
 * Fixtures-only trust anchor fingerprint map.
 *
 * **Not for production use.** The fixtures CA under \`test-ca.pem\` is
 * generated by \`spec/tools/fixtures-ca.ts\` and is only referenced by the
 * \`fail-trust-anchor-mismatch\` test vector. A CI check asserts this map
 * has empty set-intersection with \`src/trust-anchors/fingerprints.ts\`
 * so a fixtures anchor cannot leak into a production verifier's trust set.
 *
 * Regenerated by \`npm run fixtures:generate\`. Do not hand-edit.
 */
export const TRUST_ANCHOR_FINGERPRINTS_FIXTURES: Record<string, string> = {
  'test-ca.pem': '${fixtures.caSkiSha256Hex}',
};
`,
  );
  console.log(`  wrote fixtures-trust-anchors/fingerprints.ts`);

  console.log('\n[vectors] regenerating crypto-bearing reference test vectors');
  await generateTier1Pass();
  await generateTier2Pass({ caSkiSha256Hex: fixtures.caSkiSha256Hex });
  await generatePartialMissingAnchor();
  await generateTrustAnchorMismatch({ fixtures });

  console.log('\n[done] four crypto-bearing vectors regenerated. Run `npm test` to verify.');
}

const isDirectInvocation = import.meta.url === `file://${process.argv[1]}`;
if (isDirectInvocation) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
