/**
 * verifyBundle integration tests.
 *
 * Covers:
 * - Happy path: full valid Tier 2 bundle → verdict: 'pass'
 * - Happy path: Tier 1 bundle (no event/signature fields) → verdict: 'pass'
 * - Tier 2 with single-leaf Merkle tree
 * - Edge: empty anchors array → fail
 * - Error: tampered event hash
 * - Error: tampered Merkle sibling
 * - Error: unsupported bundle_schema_version
 * - Error: pending bundle (no merkle_proof/anchors) → fail (no anchors)
 * - Solana: memo content mismatch (via mocked fetch)
 * - Solana: RPC returns null transaction
 * - Ed25519: bad signature
 * - Ed25519: signing key not found in signing_keys
 *
 * TSA token verification is covered in tsa.test.ts.
 * Real Solana devnet fetch is gated behind SOLANA_DEVNET_INTEGRATION.
 */

import { describe, it, expect, vi, afterEach } from 'vitest';

import { verifyBundle } from './core.js';
import type { VerificationBundle } from './types.js';

// ---------------------------------------------------------------------------
// Pre-computed test fixtures
// (generated by running the fixture script against the production algorithm)
// ---------------------------------------------------------------------------

// Event hash of a canonical HashInputV2 object:
//   { deal_id: 'deal-123', event_type: 'ACCEPT_TERMS', actor_user_id: 'user-456',
//     actor_org_id: 'org-789', actor_role: 'talent',
//     timestamp: '2026-04-15T10:00:00.000Z', prev_event_hash: null,
//     metadata: { fromStatus: 'negotiating', toStatus: 'pending_contract' },
//     artifact_references: [] }
const TEST_EVENT_HASH = '700a3a62664702893e5fb5529d26b053d90b593ede16facb99ad62abe8ead9e1';

// Corresponding event object (the Tier 2 bundle's 'event' field)
const TEST_EVENT: Record<string, unknown> = {
  deal_id: 'deal-123',
  event_type: 'ACCEPT_TERMS',
  actor_user_id: 'user-456',
  actor_org_id: 'org-789',
  actor_role: 'talent',
  timestamp: '2026-04-15T10:00:00.000Z',
  prev_event_hash: null,
  metadata: { fromStatus: 'negotiating', toStatus: 'pending_contract' },
  artifact_references: [],
};

// Ed25519 test key (deterministic — do not use in production)
const TEST_KEY_FINGERPRINT = '2f800cb46b72f87e';
const TEST_KEY_BASE64URL = 'VMDHft-Qgh--i0MGvnxPMcXgoGGl6G2b1-me0WWtxcM';
// Signature over TEST_EVENT_HASH bytes with the above key
const TEST_EVENT_HASH_SIG =
  '5131f09666de9de21fc07ffa979fb1f47e19f3ee2d8cbd9ed33b994f55d1e28a505ae8e0a1f52b989c8096fa821e4d5e89874090010a5d49132cf5e424a06408';

// Single-leaf Merkle tree: root = SHA-256(0x00 || hex_decode(TEST_EVENT_HASH))
// Computed: f6512d82aa4850e4f5e272829bbdbf8dbc2f6b28e0f430c1b52c414d9fe276b0
const TEST_SINGLE_LEAF_ROOT = 'f6512d82aa4850e4f5e272829bbdbf8dbc2f6b28e0f430c1b52c414d9fe276b0';

// Two-event batch: [EH1='aaa...', EH2='bbb...'], EH1 at index 0
const EH1 = 'a'.repeat(64);
const TWO_LEAF_ROOT = '03938e2c8f758e6cae443d499b41c899c373eb0c0198bae61796a069f2b05904';
const EH2_LEAF_HASH = '4f16119d36ccd0da91102f57692d73934fd0ad2494280df88449accedbbfb7ea';

// ---------------------------------------------------------------------------
// Bundle factories
// ---------------------------------------------------------------------------

/** Solana anchor record for a confirmed bundle. */
const SOLANA_ANCHOR = {
  type: 'solana' as const,
  signature: 'testSolanaSignature11111111111111111111111111111111111111111',
  cluster: 'mainnet-beta',
};

/** Factory: minimal Tier 1 bundle with single-leaf Merkle tree for TEST_EVENT_HASH */
function makeTier1Bundle(overrides?: Partial<VerificationBundle>): VerificationBundle {
  return {
    bundle_schema_version: 1,
    status: 'confirmed',
    event_hash: TEST_EVENT_HASH,
    merkle_proof: {
      leaf_index: 0,
      siblings: [],
      root: TEST_SINGLE_LEAF_ROOT,
    },
    anchors: [SOLANA_ANCHOR],
    partial_anchors_reason: [],
    ...overrides,
  };
}

/** Factory: Tier 2 bundle with canonical event + Ed25519 signature */
function makeTier2Bundle(overrides?: Partial<VerificationBundle>): VerificationBundle {
  return {
    bundle_schema_version: 1,
    status: 'confirmed',
    event_hash: TEST_EVENT_HASH,
    event: TEST_EVENT,
    server_signature: TEST_EVENT_HASH_SIG,
    signing_key_id: TEST_KEY_FINGERPRINT,
    signing_keys: [
      {
        fingerprint: TEST_KEY_FINGERPRINT,
        public_key_base64url: TEST_KEY_BASE64URL,
        status: 'active',
      },
    ],
    merkle_proof: {
      leaf_index: 0,
      siblings: [],
      root: TEST_SINGLE_LEAF_ROOT,
    },
    anchors: [SOLANA_ANCHOR],
    partial_anchors_reason: [],
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Mock fetch for Solana RPC
// ---------------------------------------------------------------------------

function mockSolanaRpc(options: {
  tx?: {
    slot?: number;
    blockTime?: number;
    logMessages?: string[];
  } | null;
  httpError?: boolean;
}) {
  return vi.fn().mockImplementation(async () => {
    if (options.httpError) {
      return { ok: false, status: 500, statusText: 'Internal Server Error' };
    }
    const tx = options.tx;
    return {
      ok: true,
      json: async () => ({
        jsonrpc: '2.0',
        id: 1,
        result:
          tx === null
            ? null
            : tx === undefined
              ? null
              : {
                  slot: tx.slot ?? 12345,
                  blockTime: tx.blockTime ?? 1713000000,
                  meta: { logMessages: tx.logMessages ?? [] },
                },
      }),
    };
  });
}

// ---------------------------------------------------------------------------
// Helper: run verifyBundle with a mocked fetch for Solana
// ---------------------------------------------------------------------------

async function runWithFetch(
  bundle: VerificationBundle,
  fetchMock: ReturnType<typeof mockSolanaRpc>,
  opts?: Parameters<typeof verifyBundle>[1],
) {
  const originalFetch = global.fetch;
  global.fetch = fetchMock as unknown as typeof fetch;
  try {
    return await verifyBundle(bundle, opts);
  } finally {
    global.fetch = originalFetch;
  }
}

afterEach(() => {
  vi.restoreAllMocks();
});

// ---------------------------------------------------------------------------
// Tests: bundle_schema_version
// ---------------------------------------------------------------------------

describe('bundle_schema_version', () => {
  it('fails with unsupported version', async () => {
    const bundle: VerificationBundle = {
      bundle_schema_version: 99,
      status: 'confirmed',
      event_hash: TEST_EVENT_HASH,
    };
    const result = await verifyBundle(bundle);
    expect(result.verdict).toBe('fail');
    const versionCheck = result.checks.find((c) => c.check === 'bundle_schema_version');
    expect(versionCheck?.status).toBe('fail');
    expect(versionCheck?.details).toContain('unsupported bundle version: 99');
  });

  it('passes for version 1', async () => {
    const fetchMock = mockSolanaRpc({
      tx: {
        logMessages: [`Program log: Memo (len 64): "${TEST_SINGLE_LEAF_ROOT}"`],
      },
    });
    const result = await runWithFetch(makeTier1Bundle(), fetchMock);
    const versionCheck = result.checks.find((c) => c.check === 'bundle_schema_version');
    expect(versionCheck?.status).toBe('pass');
  });
});

// ---------------------------------------------------------------------------
// Tests: Tier 1 (no event / no server_signature)
// ---------------------------------------------------------------------------

describe('Tier 1 bundle (no event field)', () => {
  it('passes with single-leaf Merkle tree and confirmed Solana memo', async () => {
    const fetchMock = mockSolanaRpc({
      tx: {
        logMessages: [`Program log: Memo (len 64): "${TEST_SINGLE_LEAF_ROOT}"`],
      },
    });
    const result = await runWithFetch(makeTier1Bundle(), fetchMock);
    expect(result.verdict).toBe('pass');
    // canonical_recompute and server_signature checks must NOT appear (Tier 1)
    const checkNames = result.checks.map((c) => c.check);
    expect(checkNames).not.toContain('canonical_recompute');
    expect(checkNames).not.toContain('server_signature');
  });

  it('records the rpc_endpoint_used', async () => {
    const fetchMock = mockSolanaRpc({
      tx: { logMessages: [`Program log: Memo (len 64): "${TEST_SINGLE_LEAF_ROOT}"`] },
    });
    const result = await runWithFetch(makeTier1Bundle(), fetchMock, {
      solanaRpcUrl: 'https://custom-rpc.example.com',
    });
    expect(result.rpc_endpoint_used).toBe('https://custom-rpc.example.com');
  });
});

// ---------------------------------------------------------------------------
// Tests: Tier 2 (has event + server_signature)
// ---------------------------------------------------------------------------

describe('Tier 2 bundle (has event + server_signature)', () => {
  it('passes with valid canonical hash and Ed25519 signature', async () => {
    const fetchMock = mockSolanaRpc({
      tx: { logMessages: [`Program log: Memo (len 64): "${TEST_SINGLE_LEAF_ROOT}"`] },
    });
    const result = await runWithFetch(makeTier2Bundle(), fetchMock);
    expect(result.verdict).toBe('pass');
    const canonCheck = result.checks.find((c) => c.check === 'canonical_recompute');
    expect(canonCheck?.status).toBe('pass');
    const sigCheck = result.checks.find((c) => c.check === 'server_signature');
    expect(sigCheck?.status).toBe('pass');
  });

  it('fails on tampered event hash (canonical recompute mismatch)', async () => {
    const fetchMock = mockSolanaRpc({ tx: null });
    const result = await runWithFetch(makeTier2Bundle({ event_hash: 'f'.repeat(64) }), fetchMock);
    expect(result.verdict).toBe('fail');
    const canonCheck = result.checks.find((c) => c.check === 'canonical_recompute');
    expect(canonCheck?.status).toBe('fail');
    expect(canonCheck?.details).toContain('hash mismatch');
  });

  it('fails when signing_key_id not found in signing_keys', async () => {
    const fetchMock = mockSolanaRpc({ tx: null });
    const result = await runWithFetch(
      makeTier2Bundle({ signing_key_id: 'nonexistent-key' }),
      fetchMock,
    );
    expect(result.verdict).toBe('fail');
    const sigCheck = result.checks.find((c) => c.check === 'server_signature');
    expect(sigCheck?.status).toBe('fail');
    expect(sigCheck?.details).toContain('nonexistent-key');
  });

  it('fails with a bad Ed25519 signature', async () => {
    const fetchMock = mockSolanaRpc({ tx: null });
    const result = await runWithFetch(
      makeTier2Bundle({ server_signature: 'b'.repeat(128) }),
      fetchMock,
    );
    expect(result.verdict).toBe('fail');
    const sigCheck = result.checks.find((c) => c.check === 'server_signature');
    expect(sigCheck?.status).toBe('fail');
  });
});

// ---------------------------------------------------------------------------
// Tests: Merkle inclusion
// ---------------------------------------------------------------------------

describe('Merkle inclusion', () => {
  it('passes for single-leaf tree (empty siblings)', async () => {
    const fetchMock = mockSolanaRpc({
      tx: { logMessages: [`Program log: Memo (len 64): "${TEST_SINGLE_LEAF_ROOT}"`] },
    });
    const result = await runWithFetch(makeTier1Bundle(), fetchMock);
    const merkleCheck = result.checks.find((c) => c.check === 'merkle_inclusion');
    expect(merkleCheck?.status).toBe('pass');
  });

  it('fails on tampered Merkle sibling', async () => {
    const fetchMock = mockSolanaRpc({ tx: null });
    const bundle = makeTier1Bundle({
      merkle_proof: {
        leaf_index: 0,
        siblings: [{ hash: 'f'.repeat(64), direction: 'right' }],
        root: TEST_SINGLE_LEAF_ROOT,
      },
    });
    const result = await runWithFetch(bundle, fetchMock);
    expect(result.verdict).toBe('fail');
    const merkleCheck = result.checks.find((c) => c.check === 'merkle_inclusion');
    expect(merkleCheck?.status).toBe('fail');
  });

  it('passes for two-leaf tree with correct proof', async () => {
    const fetchMock = mockSolanaRpc({
      tx: { logMessages: [`Program log: Memo (len 64): "${TWO_LEAF_ROOT}"`] },
    });
    const bundle: VerificationBundle = {
      bundle_schema_version: 1,
      status: 'confirmed',
      event_hash: EH1,
      merkle_proof: {
        leaf_index: 0,
        // Proof for EH1 (index 0): sibling is leaf(EH2) with direction 'right'
        siblings: [{ hash: EH2_LEAF_HASH, direction: 'right' }],
        root: TWO_LEAF_ROOT,
      },
      anchors: [{ type: 'solana', signature: 'testSig', cluster: 'mainnet-beta' }],
      partial_anchors_reason: [],
    };
    const result = await runWithFetch(bundle, fetchMock);
    const merkleCheck = result.checks.find((c) => c.check === 'merkle_inclusion');
    expect(merkleCheck?.status).toBe('pass');
  });
});

// ---------------------------------------------------------------------------
// Tests: Empty anchors
// ---------------------------------------------------------------------------

describe('empty anchors', () => {
  it('fails with "no anchors" when anchors array is empty on confirmed bundle', async () => {
    const result = await verifyBundle(
      makeTier1Bundle({ anchors: [], merkle_proof: makeTier1Bundle().merkle_proof }),
    );
    expect(result.verdict).toBe('fail');
    const anchorsCheck = result.checks.find((c) => c.check === 'anchors');
    expect(anchorsCheck?.status).toBe('fail');
    expect(anchorsCheck?.details).toContain('no anchors');
  });
});

// ---------------------------------------------------------------------------
// Tests: Solana anchor
// ---------------------------------------------------------------------------

describe('Solana anchor', () => {
  it('passes when memo log contains the Merkle root', async () => {
    const fetchMock = mockSolanaRpc({
      tx: {
        slot: 99999,
        logMessages: [`Program log: Memo (len 64): "${TEST_SINGLE_LEAF_ROOT}"`],
      },
    });
    const result = await runWithFetch(makeTier1Bundle(), fetchMock);
    const solanaCheck = result.checks.find((c) => c.check === 'anchor:solana');
    expect(solanaCheck?.status).toBe('pass');
    expect(solanaCheck?.details).toContain('slot=99999');
  });

  it('fails when Solana RPC returns null transaction', async () => {
    const fetchMock = mockSolanaRpc({ tx: null });
    const result = await runWithFetch(makeTier1Bundle(), fetchMock);
    expect(result.verdict).toBe('fail');
    const solanaCheck = result.checks.find((c) => c.check === 'anchor:solana');
    expect(solanaCheck?.status).toBe('fail');
    expect(solanaCheck?.details).toContain('solana anchor not found');
  });

  it('fails when memo log does not contain the Merkle root', async () => {
    const fetchMock = mockSolanaRpc({
      tx: {
        logMessages: [
          'Program log: Memo (len 64): "differentroot111111111111111111111111111111111111111111111111111111"',
        ],
      },
    });
    const result = await runWithFetch(makeTier1Bundle(), fetchMock);
    expect(result.verdict).toBe('fail');
    const solanaCheck = result.checks.find((c) => c.check === 'anchor:solana');
    expect(solanaCheck?.status).toBe('fail');
  });
});

// ---------------------------------------------------------------------------
// Tests: partial verdict
// ---------------------------------------------------------------------------

describe('partial verdict', () => {
  it('returns partial when bundle has partial_anchors_reason and all checks pass', async () => {
    const fetchMock = mockSolanaRpc({
      tx: { logMessages: [`Program log: Memo (len 64): "${TEST_SINGLE_LEAF_ROOT}"`] },
    });
    const bundle = makeTier1Bundle({
      status: 'partial',
      partial_anchors_reason: ['tsa_freetsa'],
    });
    const result = await runWithFetch(bundle, fetchMock);
    expect(result.verdict).toBe('partial');
  });

  it('returns fail (not partial) when a check fails even with partial_anchors_reason', async () => {
    const fetchMock = mockSolanaRpc({ tx: null }); // Solana fails
    const bundle = makeTier1Bundle({
      status: 'partial',
      partial_anchors_reason: ['tsa_freetsa'],
    });
    const result = await runWithFetch(bundle, fetchMock);
    expect(result.verdict).toBe('fail');
  });
});

// ---------------------------------------------------------------------------
// Tests: pending bundle
// ---------------------------------------------------------------------------

describe('pending bundle', () => {
  it('returns partial when status is pending and no merkle_proof/anchors', async () => {
    const bundle: VerificationBundle = {
      bundle_schema_version: 1,
      status: 'pending',
      event_hash: TEST_EVENT_HASH,
    };
    const result = await verifyBundle(bundle);
    expect(result.verdict).toBe('partial');
    expect(result.checks.some((c) => c.check === 'anchoring' && c.status === 'skip')).toBe(true);
  });

  it('returns fail when pending Tier 2 bundle has tampered event (canonical recompute mismatch)', async () => {
    const bundle: VerificationBundle = {
      bundle_schema_version: 1,
      status: 'pending',
      event_hash: TEST_EVENT_HASH,
      event: { tampered: true } as Record<string, unknown>,
      server_signature: 'a'.repeat(128),
      signing_key_id: 'fp12345678901234',
      signing_keys: [
        {
          fingerprint: 'fp12345678901234',
          public_key_base64url: 'AAAA',
          status: 'active' as const,
        },
      ],
    };
    const result = await verifyBundle(bundle);
    expect(result.verdict).toBe('fail');
    expect(
      result.checks.some((c) => c.check === 'canonical_recompute' && c.status === 'fail'),
    ).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Integration: real Solana devnet (gated)
// ---------------------------------------------------------------------------

describe.skipIf(!process.env['SOLANA_DEVNET_INTEGRATION'])('Solana devnet integration', () => {
  it('fetches a real devnet transaction and verifies memo', async () => {
    const sig = process.env['SOLANA_TEST_SIG'];
    const root = process.env['SOLANA_TEST_ROOT'];
    if (!sig || !root) {
      throw new Error(
        'SOLANA_DEVNET_INTEGRATION requires SOLANA_TEST_SIG and SOLANA_TEST_ROOT env vars',
      );
    }

    // Build a single-leaf bundle for this root
    const { sha256 } = await import('@noble/hashes/sha2.js');
    const { bytesToHex, hexToBytes } = await import('@noble/hashes/utils.js');
    function leafHash(h: string): string {
      const hf = sha256.create();
      hf.update(new Uint8Array([0x00]));
      hf.update(hexToBytes(h));
      return bytesToHex(hf.digest());
    }
    const singleRoot = leafHash(root);

    const bundle: VerificationBundle = {
      bundle_schema_version: 1,
      status: 'confirmed',
      event_hash: root, // treating root as the event hash for this test
      merkle_proof: { leaf_index: 0, siblings: [], root: singleRoot },
      anchors: [{ type: 'solana', signature: sig, cluster: 'devnet' }],
      partial_anchors_reason: [],
    };

    const result = await verifyBundle(bundle, {
      solanaRpcUrl: 'https://api.devnet.solana.com',
    });
    const solanaCheck = result.checks.find((c) => c.check === 'anchor:solana');
    expect(solanaCheck?.status).toBe('pass');
  });
});
